<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tests.ComputeSystem</RootNamespace>
    <AssemblyName>VL.Fuse.Tests</AssemblyName>
    <StartupObject>Tests.ComputeSystem.Program</StartupObject>
  </PropertyGroup>

  <!-- Reference Stride packages for Int3 and other dependencies -->
  <ItemGroup>
    <PackageReference Include="Stride.Core.Mathematics" Version="4.1.0.1734" />
  </ItemGroup>

</Project>
