<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>Fuse.IO</AssemblyName>
        <RootNamespace>Fuse.IO</RootNamespace>
        <OutputPath>..\..\lib\</OutputPath>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="VL.Core" Version="2025.7.0"/>
        <PackageReference Include="VL.Stride.Runtime" Version="2025.7.0"/>
        <PackageReference Include="AssimpNet" Version="5.0.0-beta1"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="VL.Core"/>
        <Using Include="VL.Core.Import"/>
        <Using Include="VL.Lib.Collections"/>
        <Using Include="Stride.Core.Mathematics"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="Font\Tools\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
