<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyName>VL.E57</AssemblyName>
        <RootNamespace>VL.E57</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aardvark.Base" Version="5.3.13"/>
        <PackageReference Include="Aardvark.Data.E57" Version="5.5.7"/>
        <PackageReference Include="Aardvark.Geometry.PointSet" Version="5.5.7"/>
        <PackageReference Include="Aardvark.Geometry.PointTree" Version="5.5.7"/>
        <PackageReference Include="VL.Core" Version="2025.7.0-0349-g7f1d700e80"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="VL.Core"/>
        <Using Include="VL.Core.Import"/>
        <Using Include="VL.Lib.Collections"/>
        <Using Include="Stride.Core.Mathematics"/>
    </ItemGroup>

</Project>
