<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1701;1702;1591</NoWarn>
        <AssemblyName>Fuse.Compute</AssemblyName>
        <RootNamespace>Fuse.compute</RootNamespace>
        <OutputPath>..\..\lib\</OutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
        <PackageRepositories>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..'))</PackageRepositories>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="VL.Core" Version="2025.7.0"/>
        <PackageReference Include="VL.Stride.Runtime" Version="2025.7.0">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fuse\Fuse.csproj"/>
    </ItemGroup>

</Project>
