<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VLAssetBehavior>RelativeToOutput</VLAssetBehavior>
    <VLCleanBuildDirectory>True</VLCleanBuildDirectory>
    <VLExportPath>$(MsBuildThisFileDirectory)..\..\..\..\..\..\..\OneDrive\Dokumente\vvvv\gamma-preview\Exports</VLExportPath>
    <VLIgnoreCompileErrors>False</VLIgnoreCompileErrors>
    <VLIgnoreUnhandledExceptions>False</VLIgnoreUnhandledExceptions>
    <OutputType>WinExe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>